### ISSUE TITLE
Correct maintainer for aubo_trajectory_filters

### ISSUE THREAD

**Issue by shaun-edwards** [auboliuxin/aubo_robot#2]
The maintainer for `aubu_trajectory_filters` still lists myself ([here](https://github.com/auboliuxin/aubo_robot/blob/master/aubo_trajectory_filters/package.xml#L15)) - left over from the ROS-I port.  As a result, I get emails when there is a build failure.  Could you please update the maintainer email to someone from the Aubo team...or better yet, why not just depend on our ROS-I package?

**Comment by gavanderhoorn** [comment]
Yeah. It doesn't make much sense to copy this package and then *not* update the `maintainer` tag. Right now the ROS wiki page for [aubo_trajectory_filters](http://wiki.ros.org/action/diff/aubo_trajectory_filters) shows this:

![aubo_sshot](https://cloud.githubusercontent.com/assets/4550046/20639564/b3a64b56-b3c7-11e6-9dc0-164e264c972d.png)

@auboliuxin: please fix this ASAP. Either use the ROS-I package directly (as @shaun-edwards suggested), or update the maintainer (and issue tracker) information.

**Comment by 130s** [comment]
Opened a PR #6 to fix this.

**Comment by 130s** [comment]
Seems to be resolved by the repo owner's direct commit instead of #6
